---
title: My-Own-Suite
logo: false
icon: mdi:cube-outline
header: true
description: Self-hosted services dashboard
theme: default
color: zinc
cardBlur: md
columns: 3
layout:
  - Password Manager:
      style: row
      columns: 1