import type { SuiteManagerConfig } from '../../../config.ts';

function csvCell(value: string): string {
  const normalized = value.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  return `"${normalized.replace(/"/g, '""')}"`;
}

function loginRow(values: {
  name: string;
  notes?: string;
  password: string;
  uri: string;
  username: string;
}): string {
  const columns = [
    '',
    '',
    'login',
    values.name,
    values.notes || '',
    '',
    '0',
    values.uri,
    values.username,
    values.password,
    '',
  ];

  return columns.map(csvCell).join(',');
}

export function buildVaultwardenImportCsv(config: SuiteManagerConfig): string {
  const rows = [
    [
      'folder',
      'favorite',
      'type',
      'name',
      'notes',
      'fields',
      'reprompt',
      'login_uri',
      'login_username',
      'login_password',
      'login_totp',
    ].map(csvCell).join(','),
  ];

  if (config.generatedAccounts.seafile) {
    rows.push(
      loginRow({
        name: 'Seafile',
        notes: 'Generated by My Own Suite during initial setup.',
        password: config.generatedAccounts.seafile.password,
        uri: config.appUrls.seafile,
        username: config.generatedAccounts.seafile.email,
      }),
    );
  }

  if (config.generatedAccounts.radicale) {
    rows.push(
      loginRow({
        name: 'Radicale',
        notes: 'Use this for your CalDAV/CardDAV clients.',
        password: config.generatedAccounts.radicale.password,
        uri: config.appUrls.radicale,
        username: config.generatedAccounts.radicale.username,
      }),
    );
  }

  return rows.join('\n');
}
