import type { SuiteManagerConfig } from '../../../config.ts';

type VaultwardenImportEntry = {
  name: string;
  notes?: string;
  password: string;
  uri: string;
  username: string;
};

function csvCell(value: string): string {
  const normalized = value.replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  return `"${normalized.replace(/"/g, '""')}"`;
}

function loginRow(values: VaultwardenImportEntry): string {
  const columns = [
    '',
    '',
    'login',
    values.name,
    values.notes || '',
    '',
    '0',
    values.uri,
    values.username,
    values.password,
    '',
  ];

  return columns.map(csvCell).join(',');
}

export function getVaultwardenImportEntries(config: SuiteManagerConfig): VaultwardenImportEntry[] {
  const entries: VaultwardenImportEntry[] = [
    {
      name: 'My Own Suite | Suite Manager',
      notes: 'Use this to sign in to the My Own Suite control plane.',
      password: config.ownerPassword,
      uri: config.appUrls.suiteManager,
      username: config.ownerEmail,
    },
  ];

  if (config.generatedAccounts.seafile) {
    entries.push({
        name: 'Seafile',
        notes: 'Generated by My Own Suite during initial setup.',
        password: config.generatedAccounts.seafile.password,
        uri: config.appUrls.seafile,
        username: config.generatedAccounts.seafile.email,
      });
  }

  if (config.generatedAccounts.radicale) {
    entries.push({
        name: 'Radicale',
        notes: 'Use this for your CalDAV/CardDAV clients.',
        password: config.generatedAccounts.radicale.password,
        uri: config.appUrls.radicale,
        username: config.generatedAccounts.radicale.username,
      });
  }

  return entries;
}

export function buildVaultwardenImportCsv(config: SuiteManagerConfig): string {
  const rows = [
    [
      'folder',
      'favorite',
      'type',
      'name',
      'notes',
      'fields',
      'reprompt',
      'login_uri',
      'login_username',
      'login_password',
      'login_totp',
    ].map(csvCell).join(','),
    ...getVaultwardenImportEntries(config).map(loginRow),
  ];

  return rows.join('\n');
}
