const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const { syncBranding } = require('../scripts/sync-branding.cjs');

const v2Root = path.resolve(__dirname, '..');

test('branding sync writes shared CSS to V2 targets from the canonical source', () => {
  syncBranding();

  const canonical = fs.readFileSync(path.join(v2Root, 'branding', 'styles', 'mos.css'), 'utf8');
  const siteCss = fs.readFileSync(path.join(v2Root, 'site', 'generated', 'branding', 'mos.css'), 'utf8');
  const suiteCss = fs.readFileSync(path.join(v2Root, 'suite-manager', 'frontend', 'src', 'styles', 'mos.css'), 'utf8');
  const homepageCss = fs.readFileSync(path.join(v2Root, 'infrastructure', 'homepage', 'custom.css'), 'utf8');

  assert.match(siteCss, /Generated by version-2\/scripts\/sync-branding\.cjs/);
  assert.match(suiteCss, /Generated by version-2\/scripts\/sync-branding\.cjs/);
  assert.match(siteCss, /--mos-color-accent: #63e2b3;/);
  assert.match(suiteCss, /--mos-color-accent: #63e2b3;/);
  assert.match(homepageCss, /--color-500: 99 226 179;/);
  assert.ok(siteCss.endsWith(canonical));
  assert.ok(suiteCss.endsWith(canonical));
});
