import apps from '../generated/mos-apps.json';
import type { IconRef } from './roadmap-model';

// Generated by scripts/prepare-assets.mjs from apps/*/manifest.json — the same
// source of truth the site catalog and Suite Manager use, so every app that
// enters the MOS catalog automatically becomes a suggested replacement here.
export interface MosApp {
  id: string;
  name: string;
  summary: string;
  category: string;
  replaces: string[];
  hasIcon: boolean;
}

export const mosApps = apps as MosApp[];

export const MOS_ICON_PREFIX = 'mos-app-';

export const mosAppIconUrl = (id: string) =>
  `${import.meta.env.BASE_URL}mos-apps/${encodeURIComponent(id)}.png`;

export const mosAppDocsUrl = (id: string) =>
  `https://myownsuite.org/docs/apps/${encodeURIComponent(id)}/`;

const normalize = (value: string) => value.toLowerCase().replace(/[^a-z0-9]/g, '');

export function mosAppForIcon(icon: IconRef): MosApp | undefined {
  if (icon.id.startsWith(MOS_ICON_PREFIX)) {
    const id = icon.id.slice(MOS_ICON_PREFIX.length);
    return mosApps.find((app) => app.id === id);
  }
  const iconId = normalize(icon.id);
  const iconName = normalize(icon.name);
  return mosApps.find((app) => {
    const appId = normalize(app.id);
    const appName = normalize(app.name);
    return appId === iconId || appName === iconId || appName === iconName;
  });
}

export function mosAppsForIcons(icons: IconRef[]): MosApp[] {
  const matched = new Map<string, MosApp>();
  for (const icon of icons) {
    const app = mosAppForIcon(icon);
    if (app) matched.set(app.id, app);
  }
  return [...matched.values()];
}

export function mosAppMatchesQuery(app: MosApp, query: string): boolean {
  const terms = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
  if (!terms.length) return true;
  const haystack = [app.id, app.name, app.summary, app.category, ...app.replaces]
    .join(' ')
    .toLowerCase();
  return terms.every((term) => haystack.includes(term));
}

export async function createMosAppIcon(app: MosApp): Promise<IconRef> {
  const response = await fetch(mosAppIconUrl(app.id));
  if (!response.ok)
    throw new Error(`The ${app.name} icon could not be loaded.`);
  const blob = await response.blob();
  const dataUrl = await new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () =>
      typeof reader.result === 'string'
        ? resolve(reader.result)
        : reject(new Error(`The ${app.name} icon could not be read.`));
    reader.onerror = () =>
      reject(new Error(`The ${app.name} icon could not be read.`));
    reader.readAsDataURL(blob);
  });
  return {
    id: `${MOS_ICON_PREFIX}${app.id}`,
    name: app.name,
    source: 'dashboard',
    dataUrl,
    attribution: 'My Own Suite app catalog',
  };
}
