---
# Bookmarks for Railway Homepage

- Releases:
    - Source Code:
        - abbr: GH
          href: https://github.com/rpuls/my-own-suite

- Social:
    - Community:
        - abbr: DC
          href: https://discord.gg/K72wyWRt

- Docs:
    - Documentation:
        - abbr: DOC
          href: https://myownsuite.org/docs/
