import fs from 'node:fs';
import path from 'node:path';

import YAML from 'yaml';

import type { InstalledCatalogState } from './types.ts';

export type ComposeSelectionOutput = {
  apps: Array<{
    id: string;
    lastApply: {
      message: string | null;
      status: 'pending' | 'succeeded' | 'failed';
      updatedAt: string;
    } | null;
    services: string[];
    status: string;
  }>;
  generatedAt: string;
  profiles: string[];
  services: string[];
  version: 1;
};

export type WrittenComposeSelection = {
  composeYaml: string;
  jsonPath: string;
  selection: ComposeSelectionOutput;
  selectionJson: string;
  yamlPath: string;
};

function uniqueSorted(values: string[]): string[] {
  return Array.from(new Set(values)).sort();
}

function serviceNameFromServiceEnv(serviceEnv: string): string | null {
  const normalized = serviceEnv.replace(/\\/g, '/');
  const match = normalized.match(/^services\/([^/]+)\/\.env$/u);
  return match?.[1] || null;
}

export function buildComposeSelection(state: InstalledCatalogState, generatedAt = new Date()): ComposeSelectionOutput {
  const selectedApps = state.apps.filter((app) => app.status === 'pending-apply' || app.status === 'installed');
  const selectedServices = uniqueSorted(
    selectedApps.flatMap((app) => [
      ...app.serviceNames,
      ...(app.installPlan?.envProjections || [])
        .map((projection) => serviceNameFromServiceEnv(projection.serviceEnv))
        .filter((serviceName): serviceName is string => Boolean(serviceName)),
    ]),
  );

  return {
    apps: selectedApps
      .map((app) => ({
        id: app.appId,
        lastApply: app.lastApply,
        services: app.serviceNames,
        status: app.status,
      }))
      .sort((a, b) => a.id.localeCompare(b.id)),
    generatedAt: generatedAt.toISOString(),
    profiles: uniqueSorted(
      selectedApps
        .map((app) => app.installPlan?.composeProfile)
        .filter((profile): profile is string => Boolean(profile)),
    ),
    services: selectedServices,
    version: 1,
  };
}

export function writeComposeSelection(
  stateDir: string,
  state: InstalledCatalogState,
  generatedAt = new Date(),
): WrittenComposeSelection {
  const selection = buildComposeSelection(state, generatedAt);
  const outputDir = path.join(stateDir, 'app-catalog');
  const jsonPath = path.join(outputDir, 'compose-selection.json');
  const yamlPath = path.join(outputDir, 'docker-compose.catalog.yml');
  const selectionJson = `${JSON.stringify(selection, null, 2)}\n`;
  const composeYaml = YAML.stringify({
    name: 'mos',
    'x-mos-generated': {
      note: 'Generated by Suite Manager app catalog. Runtime compose apply is not wired yet.',
      selectedApps: selection.apps,
      selectedProfiles: selection.profiles,
      selectedServices: selection.services,
      version: selection.version,
    },
  });

  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(jsonPath, selectionJson, 'utf8');
  fs.writeFileSync(yamlPath, composeYaml, 'utf8');

  return {
    composeYaml,
    jsonPath,
    selection,
    selectionJson,
    yamlPath,
  };
}
