import fs from 'node:fs';
import path from 'node:path';

import YAML from 'yaml';

import type { InstalledCatalogState } from './types.ts';

export type ComposeSelectionOutput = {
  apps: Array<{
    id: string;
    services: string[];
    status: string;
  }>;
  generatedAt: string;
  profiles: string[];
  version: 1;
};

export type WrittenComposeSelection = {
  jsonPath: string;
  selection: ComposeSelectionOutput;
  yamlPath: string;
};

function uniqueSorted(values: string[]): string[] {
  return Array.from(new Set(values)).sort();
}

export function buildComposeSelection(state: InstalledCatalogState, generatedAt = new Date()): ComposeSelectionOutput {
  const selectedApps = state.apps.filter((app) => app.status === 'pending-apply' || app.status === 'installed');

  return {
    apps: selectedApps
      .map((app) => ({
        id: app.appId,
        services: app.serviceNames,
        status: app.status,
      }))
      .sort((a, b) => a.id.localeCompare(b.id)),
    generatedAt: generatedAt.toISOString(),
    profiles: uniqueSorted(
      selectedApps
        .map((app) => app.installPlan?.composeProfile)
        .filter((profile): profile is string => Boolean(profile)),
    ),
    version: 1,
  };
}

export function writeComposeSelection(
  stateDir: string,
  state: InstalledCatalogState,
  generatedAt = new Date(),
): WrittenComposeSelection {
  const selection = buildComposeSelection(state, generatedAt);
  const outputDir = path.join(stateDir, 'app-catalog');
  const jsonPath = path.join(outputDir, 'compose-selection.json');
  const yamlPath = path.join(outputDir, 'docker-compose.catalog.yml');
  const yaml = YAML.stringify({
    name: 'mos',
    'x-mos-generated': {
      note: 'Generated by Suite Manager app catalog. Runtime compose apply is not wired yet.',
      selectedApps: selection.apps,
      selectedProfiles: selection.profiles,
      version: selection.version,
    },
  });

  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(jsonPath, `${JSON.stringify(selection, null, 2)}\n`, 'utf8');
  fs.writeFileSync(yamlPath, yaml, 'utf8');

  return {
    jsonPath,
    selection,
    yamlPath,
  };
}
