const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const { syncBranding } = require('../../scripts/sync-branding.cjs');

const repoRoot = path.resolve(__dirname, '..', '..');

test('branding sync writes shared CSS to MOS targets from the canonical source', () => {
  syncBranding();

  const canonical = fs.readFileSync(path.join(repoRoot, 'branding', 'styles', 'mos.css'), 'utf8');
  const siteCss = fs.readFileSync(path.join(repoRoot, 'site', 'generated', 'branding', 'mos.css'), 'utf8');
  const suiteCss = fs.readFileSync(path.join(repoRoot, 'suite-manager', 'frontend', 'src', 'styles', 'mos.css'), 'utf8');
  const homepageCss = fs.readFileSync(path.join(repoRoot, 'infrastructure', 'homepage', 'custom.css'), 'utf8');
  const canonicalMark = fs.readFileSync(path.join(repoRoot, 'branding', 'my-own-suite-mark.png'));
  const homepageMark = fs.readFileSync(
    path.join(repoRoot, 'infrastructure', 'homepage', 'images', 'my-own-suite-mark.png'),
  );
  const ownerSetupSource = fs.readFileSync(
    path.join(repoRoot, 'suite-manager', 'frontend', 'src', 'features', 'setup', 'OwnerSetupScreen.tsx'),
    'utf8',
  );
  const loginSource = fs.readFileSync(
    path.join(repoRoot, 'suite-manager', 'frontend', 'src', 'features', 'auth', 'LoginScreen.tsx'),
    'utf8',
  );

  assert.match(siteCss, /Generated by scripts\/sync-branding\.cjs/);
  assert.match(suiteCss, /Generated by scripts\/sync-branding\.cjs/);
  assert.match(siteCss, /--mos-color-accent: #63e2b3;/);
  assert.match(suiteCss, /--mos-color-accent: #63e2b3;/);
  assert.match(suiteCss, /url\('\/suite-manager\/assets\/brand\/fonts\/open-sans-400\.ttf'\)/);
  assert.doesNotMatch(suiteCss, /url\('\/brand\//);
  assert.match(homepageCss, /--color-500: 99 226 179;/);
  assert.match(homepageCss, /\.service-card/);
  assert.match(homepageCss, /linear-gradient\(155deg/);
  assert.ok(siteCss.endsWith(canonical));
  assert.deepEqual(homepageMark, canonicalMark);
  for (const source of [ownerSetupSource, loginSource]) {
    assert.match(source, /\/suite-manager\/assets\/brand\/my-own-suite-mark\.png/);
    assert.doesNotMatch(source, /src="\/brand\//);
  }
});
