#!/usr/bin/env bash

set -euo pipefail

REPO_DIR="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
VPS_DIR="${REPO_DIR}/deploy/vps"
SUITE_MANAGER_SELFHOST_ENV="${VPS_DIR}/services/suite-manager/.env.selfhost"
SELFHOST_COMPOSE_OVERRIDE="${VPS_DIR}/docker-compose.selfhost.yml"
UPDATE_AGENT_INSTALLER="${REPO_DIR}/agents/selfhost/update/install.sh"
SERVICE_AGENT_INSTALLER="${REPO_DIR}/agents/selfhost/service/install.sh"
BACKUP_AGENT_INSTALLER="${REPO_DIR}/agents/selfhost/backup/install.sh"

log() {
  printf '[mos-host-agents] %s\n' "$1"
}

is_selfhost_checkout() {
  [[ -f "${SUITE_MANAGER_SELFHOST_ENV}" ]] ||
    [[ -f "${SELFHOST_COMPOSE_OVERRIDE}" ]] ||
    [[ -f /etc/mos-selfhost.env ]]
}

if [[ "$(uname -s)" != "Linux" ]]; then
  log "Skipping host-agent reconciliation outside Linux."
  exit 0
fi

if ! is_selfhost_checkout; then
  log "Skipping host-agent reconciliation because this checkout is not marked as self-host."
  exit 0
fi

if [[ "${EUID}" -ne 0 ]]; then
  log "Skipping host-agent reconciliation because root privileges are required."
  exit 0
fi

if [[ ! -f "${REPO_DIR}/package.json" ]]; then
  log "Skipping host-agent reconciliation because ${REPO_DIR} does not look like the repo root."
  exit 0
fi

if [[ -f "${UPDATE_AGENT_INSTALLER}" ]]; then
  log "Installing or refreshing self-host update agent."
  bash "${UPDATE_AGENT_INSTALLER}" "${REPO_DIR}"
else
  log "Skipping update-agent install because ${UPDATE_AGENT_INSTALLER} was not found."
fi

if [[ -f "${SERVICE_AGENT_INSTALLER}" ]]; then
  log "Installing or refreshing self-host service agent."
  bash "${SERVICE_AGENT_INSTALLER}" "${REPO_DIR}"
else
  log "Skipping service-agent install because ${SERVICE_AGENT_INSTALLER} was not found."
fi

if [[ -f "${BACKUP_AGENT_INSTALLER}" ]]; then
  log "Installing or refreshing self-host backup agent."
  bash "${BACKUP_AGENT_INSTALLER}" "${REPO_DIR}"
else
  log "Skipping backup-agent install because ${BACKUP_AGENT_INSTALLER} was not found."
fi

log "Writing Suite Manager self-host agent environment."
mkdir -p "$(dirname "${SUITE_MANAGER_SELFHOST_ENV}")"
cat > "${SUITE_MANAGER_SELFHOST_ENV}" <<'EOF'
# Generated by self-host host-agent reconciliation.
# This file lets self-host runtime wiring override the generic VPS defaults.
SUITE_MANAGER_UPDATES_AGENT_SOCKET_PATH=/run/mos-update-agent/agent.sock
SUITE_MANAGER_UPDATES_AGENT_TOKEN_FILE=/etc/mos-update-agent/auth.token
SUITE_MANAGER_SERVICE_AGENT_SOCKET_PATH=/run/mos-service-agent/agent.sock
SUITE_MANAGER_SERVICE_AGENT_TOKEN_FILE=/etc/mos-service-agent/auth.token
SUITE_MANAGER_BACKUP_AGENT_SOCKET_PATH=/run/mos-backup-agent/agent.sock
SUITE_MANAGER_BACKUP_AGENT_TOKEN_FILE=/etc/mos-backup-agent/auth.token
EOF
chmod 0600 "${SUITE_MANAGER_SELFHOST_ENV}"

log "Writing self-host Compose override."
cat > "${SELFHOST_COMPOSE_OVERRIDE}" <<'EOF'
services:
  suite-manager:
    env_file:
      - .env
      - ./services/suite-manager/.env
      - ./services/homepage/.env
      - ./services/vaultwarden/.env
      - ./services/seafile/.env
      - ./services/radicale/.env
      - ./services/suite-manager/.env.selfhost
    volumes:
      - /run/mos-update-agent:/run/mos-update-agent
      - /etc/mos-update-agent/auth.token:/etc/mos-update-agent/auth.token:ro
      - /run/mos-service-agent:/run/mos-service-agent
      - /etc/mos-service-agent/auth.token:/etc/mos-service-agent/auth.token:ro
      - /run/mos-backup-agent:/run/mos-backup-agent
      - /etc/mos-backup-agent/auth.token:/etc/mos-backup-agent/auth.token:ro
EOF

log "Host-agent reconciliation complete."
